export const constants = {
  CONNECTOR_END_SIZE: 15,
  DISTANCE_TOLERANCE: 15,
  PLUGIN_DATA_KEY_CONNECTOR: "FLOW_CONNECTOR_CONNECTOR_NODE",
  PLUGIN_DATA_KEY_NODE: "FLOW_CONNECTOR_CONNECTED_NODE",
  PLUGIN_DATA_CONNECTOR_INFO: "CONNECTOR_INFO",
  CONNECTOR_LABEL_FONT_STYLE: { family: "Inter", style: "Semi Bold" },
  CONNECTOR_LABEL_FONT_SIZE: 24,
  CONNECTOR_LABEL_PADDING: {
    x: 24, // I.E PADDING-LEFT: 12
    y: 24, // I.E PADDING-TOP: 12
  },
};
