export const constants = {
  CONNECTOR_END_SIZE: 15,
  DISTANCE_TOLERANCE: 100,
  PLUGIN_DATA_KEY_CONNECTOR: "FLOW_CONNECTOR_CONNECTOR_NODE",
  PLUGIN_DATA_KEY_NODE: "FLOW_CONNECTOR_CONNECTED_NODE",
  PLUGIN_DATA_CONNECTOR_INFO: "CONNECTOR_INFO",
  CONNECTOR_LABEL_FONT_STYLE: { family: "Inter", style: "Semi Bold" },
  CONNECTOR_LABEL_PADDING: {
    x: 16, // I.E PADDING-LEFT: 8
    y: 16, // I.E PADDING-TOP: 4
  },
};
